name: Docker  CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-frontend:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2


      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

    #   - name: Build and push Docker image to Docker Hub
    #     uses: docker/build-push-action@v2
    #     with: 
    #       context: .
    #       push: true
    #       tag: ${{ secrets.DOCKER_USERNAME }}/webapp:${{github.sha}}

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u abbeylink --password-stdin

     # - name: Build and push Docker image to Docker Hub

        # env:
        #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        #     DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        #     IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/webapp:${{github.sha}}
        # run: |
        #     docker build -t $IMAGE_NAME .
            
        #     docker push $IMAGE_NAME
        

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.EC2_HOST }}
         username: ${{ secrets.AWS_ACCESS_KEY_ID }}
         key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         script: |
           docker stop webapp || true
           docker rm webapp || true
           docker pull ${{ secrets.DOCKER_USERNAME }}/frontend-prod:1.0
           docker run -d --name webapp -p 80:80 ${{ secrets.DOCKER_USERNAME }}/frontend-prod:1.0


      