name: Docker  CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-frontend:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

     

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          tag: tar1q87/webapp:${{github.sha}}

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.EC2_HOST }}
         username: ${{ secrets.AWS_ACCESS_KEY_ID }}
         key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         script: |
           docker stop webapp || true
           docker rm webapp || true
           docker pull ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }} 
           docker run -d --name webapp -p 80:80 ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }} 

           
      - name: Archive debug logs
        if: always() # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v2
        with:
                name: debug-logs
                path: / # Replace with the actual path to your logs 
