name: Docker  CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-frontend:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2


      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

   

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image to Docker Hub

        env:

            IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/client:${{github.sha}}
        run: |
            docker build -t $IMAGE_NAME .
            
            docker push $IMAGE_NAME


      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.EC2_HOST }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.EC2_SSH_KEY }}
         script: |
           docker stop client || true
           docker rm client || true
           docker pull ${{ secrets.DOCKER_USERNAME }}/client:${{github.sha}}
           docker run -d --name webapp -p 80:80 ${{ secrets.DOCKER_USERNAME }}/client:${{github.sha}}


      
